name: Example workshop

# Accepts 'flutter' or 'dart'
type: dart

# Configuration for each step 
steps:
  - name: Why use Futures
    directory: why_use_futures
    has_solution: true
  - name: Step 2
    directory: step_02
    has_solution: false
