name: Beginner Guide to Futures

# Accepts 'flutter' or 'dart'
type: dart

# Configuration for each step 
steps:
  - name: What is a Future
    directory: 01_what_is_a_future
    has_solution: true
  - name: Create a Future
    directory: 02_creating_a_future
    has_solution: true
  - name: Using Async/Await
    directory: 03a_using_a_future
    has_solution: true
  - name: Using Then
    directory: 03b_using_a_future
    has_solution: true
  - name: Notify Errors from a Future
    directory: 04a_error_handling
    has_solution: true
  - name: Handle Errors from a Future
    directory: 04b_error_handling
    has_solution: true
  - name: Run Multiple Futures
    directory: 05a_multiple_futures
    has_solution: true
  - name: Wait For Multiple Futures
    directory: 05b_multiple_futures
    has_solution: true
  - name: Future Timeout
    directory: 06_future_timeout
    has_solution: true
